version: '3'
services:
  nginx:
    container_name: container_nginx
    build:
      context: ./docker/docker-nginx
    restart: always
    ports:
      - 80:80
    hostname: container_nginx_hostname
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    links:
      - app
  app:
    container_name: container_springboot
    restart: always
    user: $UID:$GID
    build:
      context: ./docker/docker-springboot
      args:
        UID: $UID
        GID: $GID
        UNAME: $UNAME
    expose:
      - 8080
    ports:
      - 8080:8080
    hostname: container_springboot_hostname
    working_dir: '/home/$UNAME'
    volumes:
      - ./serverside:/home/$UNAME/serverside
    command: ./serverside/gradlew bootRun
    hostname: container_springboot_hostname
