version: '3'
services:
  nginx:
    container_name: container_nginx
    build:
      context: ./docker/docker-nginx
    restart: always
    ports:
      - 80:80
    hostname: container_nginx_hostname
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    links:
      - app
  app:
    container_name: container_springboot
    restart: always
    build:
      context: ./docker/docker-springboot
    expose:
      - 8080
    ports:
      - 8080:8080
    hostname: container_springboot_hostname
    volumes:
      - ./serverside:/serverside
    working_dir: '/serverside'
    tty: true
    hostname: container_springboot_hostname
    command: java -jar /serverside/build/libs/demo-0.0.1-SNAPSHOT.jar
