version: '3'
services:
  nginx:
    container_name: container_nginx
    build: docker/docker-nginx
    restart: always
    ports:
      - 80:80
    hostname: container_nginx_hostname
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    links:
      - app
  app:
    container_name: container_springboot
    restart: always
    build: docker/docker-springboot
    expose:
      - 8080
    hostname: container_springboot_hostname
    volumes:
      - ./serverside:/serverside
    command: ./serverside/gradlew bootRun
    hostname: container_springboot_hostname
